# Generated by Django 4.2.16 on 2025-10-21 06:56

import apps.solution.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_name', models.CharField(max_length=200, verbose_name='Solution Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('detail', models.JSONField(blank=True, null=True, verbose_name='Detail Specifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solution',
                'verbose_name_plural': 'Solutions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SolutionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.solution.models.solution_image_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='solution.solution')),
            ],
            options={
                'verbose_name': 'Solution Image',
                'verbose_name_plural': 'Solution Images',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
